### ISSUE TITLE
Can't find npm module 'request'

### ISSUE THREAD

**Issue by isAlmogK** [woubuc/node-updown#2]
Using this package in a meteor app but I'm getting Can't find npm module 'request' here is the full error any ideas why it's causing a conflict 

Error: Can't find npm module 'request'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
1741
2017-01-11 22:54:26-08:00 at Object.require (/app/bundle/programs/server/boot.js:200:17)
1741
2017-01-11 22:54:26-08:00 at options.fallback (packages/modules-runtime.js:445:18)
1741
2017-01-11 22:54:26-08:00 at require (packages/modules-runtime.js:112:16)
1741
2017-01-11 22:54:26-08:00 at meteorInstall.node_modules.node-updown.lib.updown.class.js (packages/modules.js:9786:11)
1741
2017-01-11 22:54:26-08:00 at fileEvaluate (packages/modules-runtime.js:181:9)
1741
2017-01-11 22:54:26-08:00 at Module.require (packages/modules-runtime.js:106:16)
1741
2017-01-11 22:54:26-08:00 at Module.Mp.import (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
1741
2017-01-11 22:54:26-08:00 at meteorInstall.imports.api.business-uptime.methods.js (imports/api/business-uptime/methods.js:1:1)
1741
2017-01-11 22:54:26-08:00 at fileEvaluate (packages/modules-runtime.js:181:9)
1741
2017-01-11 22:54:26-08:00 at Module.require (packages/modules-runtime.js:106:16)

**Comment by woubuc** [comment]
The `request` module should be available on npm. This seems like an issue specific to Meteor. I haven't worked with Meteor myself (and as such haven't tested this with it specifically) but a quick Google search reveals [this discussion on the Meteor forum](https://forums.meteor.com/t/error-cant-find-npm-module-react-did-you-forget-to-call-npm-depends-in-package-js-within-the-modules-runtime-package/20416/5).

Could you try to install Request using `meteor npm install --save request` and then try again?

**Comment by isAlmogK** [comment]
Thanks, I believe that has fixed it
